---
version: '3.5'

networks: 
  rmoff_kafka:
    name: rmoff_kafka

services:

  broker:
    image: confluentinc/cp-kafka:5.5.0
    container_name: broker
    ports: 
      - "19092:19092"
    networks: 
      - rmoff_kafka
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092,CONNECTIONS_FROM_HOST://localhost:19092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONNECTIONS_FROM_HOST:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

        